
language: cpp
sudo: required

dist: trusty


compiler:
  - gcc

os:
  - linux


env:
  global:
    - GH_REPO_NAME: GPU_GSPCA
    - GH_REPO_REF: https://github.com/nmerrill67/GPU_GSPCA.git

notifications:
  email:
    on_success: never
    on_failure: never


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - build-essential
      - cmake
      - nvidia-375
      - nvidia-modprobe
      - libpython2.7
      - python-numpy
      - libboost-dev
      - libboost-python-dev		
      - libgsl0-dev # c++ orthogonality testing only	
script:
  - sudo reboot
  - wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb
  - sudo dpkg -i cuda-repo-ubuntu1604-9-0-local-ga2_8.0.61-1_amd64.deb
  - sudo apt update
  - sudo apt install cuda
  - sudo reboot	
  - mkdir build && cd build
  - cmake .. && make

