
language: cpp
sudo: required

dist: trusty


compiler:
  - gcc

os:
  - linux


env:
  global:
    - GH_REPO_NAME: GPU_GSPCA
    - GH_REPO_REF: https://github.com/nmerrill67/GPU_GSPCA.git

notifications:
  email:
    on_success: never
    on_failure: never


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - cmake
      - nvidia-cuda-toolkit
      - libpython2.7
      - python-numpy
      - libboost-dev
      - libboost-python-dev		
      - libgsl0-dev # c++ orthogonality testing only	
script:	
  - mkdir build && cd build
  - cmake .. && make

